[2024-07-01 00:49:31,674] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 00:49:32,000] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 02:05:26,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 02:05:26,338] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 02:45:29,679] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 02:45:30,000] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:11:23,808] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:11:23,993] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:28:31,461] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:28:31,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:38:06,049] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:38:06,234] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 03:47:33,878] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 03:47:34,234] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 04:11:58,626] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 04:11:58,939] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 04:28:45,955] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 04:28:46,269] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 04:38:00,495] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 04:38:00,868] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 04:47:40,132] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 04:47:40,423] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 05:10:25,485] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 05:10:25,842] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 05:27:40,720] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 05:27:41,158] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 05:36:27,012] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 05:36:27,452] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 05:47:32,788] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 05:47:33,054] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 06:14:35,372] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 06:14:35,578] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 06:34:48,670] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 06:34:49,095] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 06:47:30,834] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 06:47:31,042] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 07:10:38,759] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 07:10:39,179] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 07:23:18,507] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 07:23:18,807] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 07:34:19,740] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 07:34:20,139] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 07:47:51,220] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 07:47:51,543] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 08:13:20,652] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 08:13:20,837] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 08:30:33,177] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 08:30:33,541] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 08:47:33,789] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 08:47:33,987] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 09:13:01,363] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 09:13:01,647] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 09:29:52,394] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 09:29:52,874] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 09:38:57,886] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 09:38:58,211] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 09:47:28,247] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 09:47:28,463] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 10:11:37,413] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 10:11:37,593] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 10:32:43,849] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 10:32:44,173] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 10:47:46,681] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 10:47:47,121] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 11:08:27,766] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 11:08:28,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 11:20:55,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 11:20:55,738] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 11:33:31,055] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 11:33:31,260] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 11:47:56,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 11:47:57,212] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 12:18:32,505] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 12:18:32,912] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 12:52:08,409] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 12:52:08,753] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 13:13:57,957] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 13:13:58,289] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 13:28:15,048] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 13:28:15,357] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 13:35:38,272] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 13:35:38,618] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 13:47:41,693] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 13:47:41,887] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 14:09:06,944] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 14:09:07,319] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 14:26:45,398] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 14:26:45,755] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 14:36:27,942] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 14:36:28,344] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 14:47:39,267] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 14:47:39,582] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 15:09:56,621] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 15:09:56,954] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 15:25:42,221] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 15:25:42,444] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 15:33:34,715] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 15:33:35,060] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 15:47:40,601] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 15:47:40,961] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 16:11:26,926] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 16:11:27,360] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 16:30:13,269] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 16:30:13,698] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 16:42:57,053] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 16:42:57,347] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 16:49:50,742] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 16:49:51,042] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 17:09:10,648] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 17:09:11,090] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 17:27:07,750] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 17:27:08,067] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 17:35:08,052] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 17:35:08,258] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 17:47:40,917] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 17:47:41,347] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 18:12:41,248] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 18:12:41,448] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 18:31:12,299] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 18:31:12,494] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 18:47:53,030] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 18:47:53,408] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 19:08:40,236] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 19:08:40,518] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 19:20:33,976] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 19:20:34,320] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 19:33:02,907] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 19:33:03,284] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 19:47:48,475] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 19:47:48,670] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 20:10:14,426] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 20:10:14,620] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 20:24:32,521] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 20:24:32,720] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 20:33:03,871] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 20:33:04,196] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 20:47:59,962] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 20:48:00,325] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 21:09:33,575] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 21:09:33,776] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 21:24:07,924] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 21:24:08,249] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 21:33:05,430] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 21:33:05,722] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 21:47:55,496] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 21:47:55,978] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 22:09:54,340] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 22:09:54,653] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 22:27:18,850] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 22:27:19,067] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 22:35:51,171] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 22:35:51,471] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 22:47:51,217] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 22:47:51,533] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 23:09:57,306] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 23:09:57,595] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 23:23:24,585] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 23:23:24,878] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 23:33:19,838] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 23:33:20,203] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-01 23:47:46,040] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-01 23:47:46,400] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 00:42:57,643] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 00:42:58,031] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 01:47:38,952] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 01:47:39,262] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 02:28:30,154] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 02:28:30,499] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 02:46:07,682] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 02:46:08,033] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 03:10:54,498] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 03:10:54,825] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 03:27:16,945] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 03:27:17,376] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 03:36:04,339] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 03:36:04,643] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 03:47:43,702] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 03:47:43,988] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 04:13:12,618] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 04:13:12,949] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 04:30:37,319] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 04:30:37,661] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 04:47:31,267] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 04:47:31,606] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 05:10:31,337] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 05:10:31,621] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 05:27:52,595] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 05:27:52,961] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 05:36:14,415] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 05:36:14,722] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 05:47:54,368] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 05:47:54,771] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 06:14:29,474] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 06:14:29,755] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 06:33:48,759] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 06:33:49,045] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 06:47:44,475] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 06:47:44,824] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 07:10:14,460] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 07:10:14,828] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 07:24:29,782] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 07:24:30,089] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 07:33:12,501] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 07:33:12,928] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 07:47:49,387] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 07:47:49,675] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 08:12:45,595] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 08:12:45,908] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 08:29:28,919] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 08:29:29,239] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 08:39:22,059] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 08:39:22,321] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 08:47:45,061] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 08:47:45,380] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 09:10:02,393] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 09:10:02,705] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 09:24:57,604] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 09:24:57,960] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 09:33:25,897] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 09:33:26,316] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 09:47:41,528] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 09:47:41,896] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 10:10:01,636] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 10:10:01,944] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 10:29:18,720] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 10:29:19,092] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 10:38:24,500] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 10:38:24,778] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 10:47:48,797] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 10:47:49,116] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 11:08:39,538] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 11:08:39,754] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 11:20:50,308] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 11:20:50,639] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 11:34:02,300] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 11:34:02,660] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 11:47:27,385] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 11:47:27,686] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 12:17:28,911] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 12:17:29,284] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 12:49:24,867] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 12:49:25,175] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 13:12:05,400] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 13:12:05,763] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 13:26:26,359] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 13:26:26,661] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 13:33:55,317] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 13:33:55,752] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 13:47:51,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 13:47:52,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 14:09:24,002] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 14:09:24,372] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 14:25:08,361] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 14:25:08,729] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 14:33:31,618] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 14:33:32,027] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 14:47:52,561] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 14:47:52,764] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 15:09:52,022] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 15:09:52,468] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 15:23:51,239] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 15:23:51,668] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 15:33:17,538] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 15:33:17,860] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 15:48:03,064] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 15:48:03,490] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 16:12:49,825] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 16:12:50,266] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 16:32:25,113] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 16:32:25,413] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 16:47:54,173] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 16:47:54,540] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 17:08:55,001] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 17:08:55,439] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 17:26:56,549] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 17:26:56,967] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 17:34:53,838] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 17:34:54,170] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 17:47:56,517] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 17:47:56,900] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 18:12:33,532] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 18:12:33,889] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 18:31:21,017] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 18:31:21,477] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 18:47:27,585] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 18:47:27,889] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 19:09:14,451] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 19:09:14,759] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 19:20:36,965] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 19:20:37,260] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 19:33:21,806] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 19:33:22,185] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 19:47:45,383] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 19:47:45,757] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 20:10:48,396] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 20:10:48,705] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 20:26:41,917] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 20:26:42,300] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 20:35:38,399] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 20:35:38,728] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 20:47:38,605] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 20:47:38,900] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 21:09:19,415] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 21:09:19,817] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 21:22:40,143] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 21:22:40,437] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 21:33:28,796] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 21:33:29,095] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 21:47:47,271] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 21:47:47,751] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 22:09:36,885] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 22:09:37,092] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 22:27:30,635] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 22:27:30,942] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 22:35:52,193] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 22:35:52,668] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 22:47:34,621] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 22:47:34,909] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 23:09:25,484] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 23:09:25,696] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 23:23:05,237] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 23:23:05,598] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 23:33:20,815] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 23:33:21,029] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-02 23:47:52,751] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-02 23:47:53,091] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 00:42:58,350] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 00:42:58,709] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 01:47:03,227] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 01:47:03,529] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 02:27:24,156] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 02:27:24,379] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 02:44:11,387] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 02:44:11,815] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 02:51:21,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 02:51:21,379] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 03:10:35,738] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 03:10:36,025] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 03:27:07,867] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 03:27:08,186] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 03:35:31,639] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 03:35:31,853] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 03:47:32,329] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 03:47:32,630] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 04:11:36,090] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 04:11:36,446] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 04:28:23,965] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 04:28:24,254] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 04:37:37,563] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 04:37:37,752] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 04:47:56,147] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 04:47:56,491] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 05:09:35,801] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 05:09:36,145] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 05:27:43,798] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 05:27:44,112] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 05:36:11,098] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 05:36:11,517] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 05:47:55,927] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 05:47:56,278] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 06:14:29,045] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 06:14:29,370] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 06:34:23,863] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 06:34:24,307] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 06:47:30,002] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 06:47:30,363] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 07:09:20,409] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 07:09:20,627] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 07:21:56,439] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 07:21:56,740] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 07:35:02,186] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 07:35:02,486] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 07:47:53,485] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 07:47:53,919] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 08:13:02,697] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 08:13:03,003] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 08:29:59,538] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 08:29:59,818] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 08:40:00,287] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 08:40:00,584] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 08:47:37,120] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 08:47:37,410] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 09:10:30,259] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 09:10:30,545] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 09:25:32,471] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 09:25:32,871] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 09:33:12,315] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 09:33:12,548] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 09:47:44,782] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 09:47:49,212] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 10:10:40,436] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 10:10:40,673] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 10:31:01,698] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 10:31:01,907] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 10:47:50,555] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 10:47:50,869] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 11:08:41,034] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 11:08:41,486] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 11:20:49,275] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 11:20:49,662] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 11:33:07,053] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 11:33:07,421] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 11:47:44,712] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 11:47:45,038] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 12:17:49,224] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 12:17:49,534] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 12:50:40,910] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 12:50:41,350] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 13:12:16,728] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 13:12:16,945] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 13:26:48,029] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 13:26:48,410] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 13:35:54,531] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 13:35:54,854] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 13:47:41,025] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 13:47:41,300] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 14:10:59,371] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 14:10:59,596] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 14:27:30,788] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 14:27:31,157] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 14:35:47,147] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 14:35:47,392] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 14:47:59,041] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 14:47:59,275] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 15:10:03,841] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 15:10:04,112] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 15:25:43,908] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 15:25:44,368] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 15:34:25,261] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 15:34:25,579] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 15:48:00,180] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 15:48:00,473] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 16:12:30,613] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 16:12:31,081] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 16:31:24,254] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 16:31:24,574] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 16:47:37,067] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 16:47:37,375] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 17:08:56,273] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 17:08:56,553] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 17:25:57,623] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 17:25:58,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 17:33:28,544] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 17:33:28,847] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 17:47:35,805] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 17:47:36,112] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 18:12:20,812] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 18:12:21,130] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 18:29:10,049] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 18:29:10,368] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 18:38:16,193] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 18:38:16,566] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 18:47:42,292] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 18:47:42,486] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 19:07:33,785] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 19:07:34,071] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 19:19:57,141] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 19:19:57,457] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 19:33:04,456] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 19:33:04,800] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 19:47:32,415] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 19:47:32,780] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 20:10:12,600] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 20:10:13,008] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 20:24:19,474] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 20:24:19,789] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 20:33:22,615] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 20:33:22,923] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 20:47:33,160] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 20:47:33,448] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 21:10:13,820] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 21:10:14,255] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 21:23:25,751] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 21:23:25,985] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 21:34:49,985] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 21:34:50,419] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 21:47:48,826] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 21:47:49,196] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 22:09:49,109] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 22:09:49,635] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 22:27:37,330] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 22:27:37,714] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 22:36:13,478] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 22:36:13,771] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 22:47:45,072] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 22:47:45,457] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 23:10:33,452] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 23:10:33,743] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 23:25:35,531] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 23:25:36,033] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 23:33:32,835] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 23:33:33,044] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-03 23:47:54,665] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-03 23:47:55,060] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 00:43:04,472] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 00:43:04,823] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 01:47:49,379] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 01:47:49,848] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 02:28:48,138] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 02:28:48,515] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 02:46:46,912] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 02:46:47,279] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 03:12:20,528] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 03:12:20,780] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 03:29:08,896] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 03:29:09,185] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 03:38:48,848] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 03:38:49,172] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 03:47:49,051] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 03:47:49,434] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 04:11:42,585] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 04:11:42,801] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 04:28:23,213] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 04:28:23,408] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 04:38:28,013] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 04:38:28,366] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 04:47:53,041] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 04:47:53,308] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 05:11:01,668] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 05:11:01,996] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 05:28:26,333] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 05:28:26,743] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 05:36:53,323] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 05:36:53,656] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 05:47:29,225] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 05:47:29,604] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 06:13:48,055] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 06:13:48,337] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 06:33:06,211] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 06:33:06,559] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 06:47:38,366] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 06:47:38,543] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 07:10:50,128] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 07:10:50,455] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 07:23:15,717] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 07:23:16,044] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 07:33:25,592] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 07:33:25,948] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 07:47:55,856] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 07:47:56,289] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 08:13:04,903] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 08:13:05,117] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 08:30:07,389] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 08:30:07,736] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 08:39:55,960] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 08:39:56,325] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 08:47:50,942] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 08:47:51,356] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 09:10:57,653] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 09:10:58,018] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 09:27:46,130] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 09:27:46,488] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 09:36:09,908] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 09:36:10,249] 	ERROR 	104 	id_data.py 	<module>() 	Error occurred during TC ID Data process. Error: Dataframe is empty
Traceback (most recent call last):
  File "id_data.py", line 58, in <module>
    raise Exception('Dataframe is empty')
Exception: Dataframe is empty
[2024-07-04 09:47:43,972] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 09:47:45,982] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 10:10:12,210] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 10:10:14,729] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 10:28:18,913] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 10:28:21,800] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 10:36:33,863] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 10:36:36,057] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 10:47:37,479] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 10:47:40,247] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 11:10:32,430] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 11:10:34,837] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 11:24:42,160] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 11:24:44,981] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 11:33:05,048] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 11:33:07,648] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 11:47:59,907] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 11:48:02,169] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 12:17:30,114] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 12:17:32,352] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 12:50:09,993] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 12:50:12,548] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 13:12:08,349] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 13:12:10,643] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 13:26:36,666] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 13:26:39,442] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 13:34:17,465] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 13:34:20,377] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 13:47:46,209] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 13:47:48,917] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 14:09:11,309] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 14:09:13,930] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 14:26:24,443] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 14:26:26,832] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 14:35:16,638] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 14:35:18,491] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 14:47:53,021] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 14:47:56,039] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 15:09:30,706] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 15:09:33,008] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 15:24:48,860] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 15:24:50,852] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 15:33:00,325] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 15:33:02,814] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 15:47:46,494] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 15:47:48,467] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 16:11:21,397] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 16:11:23,398] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 16:30:12,652] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 16:30:15,404] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 16:40:45,633] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 16:40:47,255] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 16:48:22,500] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 16:48:24,892] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 17:09:14,611] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 17:09:17,420] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 17:26:21,332] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 17:26:23,913] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 17:33:38,975] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 17:33:40,676] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 17:47:38,601] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 17:47:41,081] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 18:12:41,426] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 18:12:43,485] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 18:30:57,726] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 18:30:59,502] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 18:47:36,562] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 18:47:39,610] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 19:08:16,838] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 19:08:19,576] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 19:20:28,084] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 19:20:30,535] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 19:32:58,339] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 19:33:00,389] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 19:47:39,748] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 19:47:42,675] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 20:09:53,539] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 20:09:55,810] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 20:24:06,002] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 20:24:08,219] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 20:33:10,646] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 20:33:13,182] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 20:48:01,848] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 20:48:03,778] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 21:09:03,574] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 21:09:05,756] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 21:22:33,379] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 21:22:35,153] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 21:34:33,369] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 21:34:35,265] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 21:47:54,675] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 21:47:56,675] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 22:09:51,425] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 22:09:54,254] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 22:27:43,342] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 22:27:46,252] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 22:36:11,740] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 22:36:13,884] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 22:47:51,099] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 22:47:53,551] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 23:09:50,096] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 23:09:52,910] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 23:23:48,769] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 23:23:51,379] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 23:33:43,433] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 23:33:45,633] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-04 23:47:50,546] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-04 23:47:53,000] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 00:42:46,354] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 00:42:48,605] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 01:47:14,927] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 01:47:17,773] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 02:27:28,608] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 02:27:31,490] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 02:44:44,054] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 02:44:46,902] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 02:51:56,194] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 02:51:58,489] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 03:11:03,318] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 03:11:10,290] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 03:27:17,249] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 03:27:19,217] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 03:35:37,885] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 03:35:39,995] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 03:48:01,153] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 03:48:03,123] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 04:13:29,826] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 04:13:31,398] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 04:31:33,575] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 04:31:35,654] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 04:47:37,743] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 04:47:39,377] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 05:09:42,196] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 05:09:44,718] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 05:26:51,852] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 05:26:54,179] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 05:35:02,407] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 05:35:04,362] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 05:47:46,203] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 05:47:48,324] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 06:14:08,754] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 06:14:10,797] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 06:33:26,473] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 06:33:28,585] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 06:47:35,751] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 06:47:37,754] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 07:09:15,716] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 07:09:17,787] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 07:21:44,358] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 07:21:47,119] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 07:33:28,595] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 07:33:31,352] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 07:47:33,904] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 07:47:37,327] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 08:12:29,195] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 08:12:31,449] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 08:28:51,932] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 08:28:54,371] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 08:38:03,539] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 08:38:05,466] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 08:47:47,269] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 08:47:49,432] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 09:11:50,029] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 09:11:52,122] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 09:27:10,423] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 09:27:12,004] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 09:35:11,154] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 09:35:13,956] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 09:48:00,115] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 09:48:02,411] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 10:10:49,083] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 10:10:51,306] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 10:29:47,153] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 10:29:49,709] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 10:38:54,790] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 10:38:57,931] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 10:47:44,967] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 10:47:46,734] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 11:08:41,352] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 11:08:44,290] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 11:21:15,237] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 11:21:16,944] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 11:33:01,068] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 11:33:04,117] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 11:47:30,792] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 11:47:33,570] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 12:16:47,176] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 12:16:49,143] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 12:49:02,757] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 12:49:05,643] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 13:11:16,088] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 13:11:18,558] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 13:26:01,031] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 13:26:05,305] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 13:33:34,468] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 13:33:37,809] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 13:47:54,070] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 13:47:57,744] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 14:09:55,122] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 14:09:57,126] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 14:26:56,849] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 14:26:59,547] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 14:35:30,492] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 14:35:32,565] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 14:47:55,545] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 14:47:58,330] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 15:09:41,342] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 15:09:43,652] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 15:25:46,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 15:25:49,283] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 15:33:20,007] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 15:33:22,534] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 15:47:36,001] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 15:47:38,555] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 16:11:34,473] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 16:11:36,682] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 16:30:04,369] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 16:30:06,469] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 16:40:39,476] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 16:40:42,647] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 16:47:42,413] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 16:47:44,678] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 17:09:14,706] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 17:09:17,594] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 17:26:53,215] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 17:26:55,376] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 17:35:01,329] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 17:35:03,155] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 17:47:51,364] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 17:47:53,281] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 18:12:31,607] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 18:12:34,042] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 18:30:47,884] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 18:30:50,028] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 18:48:04,760] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 18:48:08,271] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 19:07:37,739] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 19:07:41,643] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 19:19:49,099] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 19:19:52,623] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 19:33:21,382] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 19:33:25,036] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 19:47:47,763] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 19:47:50,651] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 20:11:12,911] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 20:11:15,068] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 20:25:24,217] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 20:25:26,126] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 20:32:55,782] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 20:32:58,068] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 20:47:44,853] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 20:47:46,805] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 21:09:32,341] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 21:09:34,719] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 21:22:58,308] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 21:23:01,628] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 21:34:53,645] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 21:34:56,816] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 21:47:47,060] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 21:47:50,021] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 22:10:38,089] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 22:10:40,344] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 22:27:49,042] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 22:27:52,156] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 22:36:23,356] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 22:36:25,100] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 22:47:54,491] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 22:47:57,629] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 23:10:03,892] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 23:10:06,202] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 23:23:24,999] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 23:23:27,092] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 23:34:53,894] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 23:34:56,231] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-05 23:47:43,067] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-05 23:47:46,454] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 00:41:38,551] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 00:41:41,258] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 01:44:37,773] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 01:44:40,109] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 02:20:59,423] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 02:21:01,744] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 02:41:54,498] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 02:41:57,963] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 02:49:04,940] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 02:49:07,348] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 03:12:27,003] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 03:12:29,364] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 03:28:53,531] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 03:28:56,877] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 03:37:02,533] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 03:37:04,896] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 03:47:46,835] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 03:47:48,585] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 04:11:47,980] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 04:11:50,709] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 04:28:45,350] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 04:28:48,015] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 04:37:57,878] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 04:38:00,265] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 04:47:49,369] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 04:47:51,973] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 05:09:38,539] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 05:09:40,781] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 05:26:18,655] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 05:26:21,030] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 05:34:02,039] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 05:34:05,043] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 05:47:52,434] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 05:47:54,364] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 06:12:13,433] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 06:12:15,829] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 06:30:36,757] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 06:30:38,953] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 06:47:31,559] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 06:47:33,526] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 07:08:16,787] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 07:08:20,816] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 07:21:53,538] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 07:21:56,189] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 07:33:01,388] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 07:33:04,284] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 07:47:32,319] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 07:47:34,342] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 08:12:46,791] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 08:12:49,847] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 08:29:04,891] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 08:29:07,849] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 08:37:54,159] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 08:37:56,021] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 08:47:47,758] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 08:47:50,572] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 09:10:30,611] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 09:10:32,912] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 09:26:08,190] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 09:26:10,156] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 09:34:09,954] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 09:34:11,878] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 09:47:58,141] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 09:47:59,845] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 10:09:14,762] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 10:09:18,116] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 10:27:18,616] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 10:27:21,857] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 10:35:19,721] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 10:35:21,985] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 10:47:57,109] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 10:47:59,537] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 11:08:14,587] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 11:08:16,970] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 11:20:22,454] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 11:20:25,809] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 11:33:15,438] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 11:33:18,684] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 11:47:36,585] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 11:47:38,827] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
[2024-07-06 12:15:24,579] 	INFO 	32 	id_data.py 	<module>() 	TC ID Data Started
[2024-07-06 12:15:27,832] 	INFO 	102 	id_data.py 	<module>() 	TC ID Data Ended
